[package]
name = "nws-forecast-zones"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
keywords = ["nws", "weather", "forecast", "zones"]
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
