[package]
name = "nws-product-list"
version = "0.1.0"
edition = "2021"
license = "CC0-1.0"
keywords = ["nws", "weather", "forecast"]
readme = "README.md"
description = "NWS Product List"
repository = "https://github.com/eminence/nws-data-parsing"

[dependencies]
